server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.159.134:33306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  cloud:
    bus:
      trace:
        enabled: true     # 开启cloud bus的跟踪
  redis:
    host: 192.168.159.134
    port: 6379
  rabbitmq:
    host: 192.168.159.134
    port: 5672
    username: guest
    password: guest
management.endpoints.web.exposure.include: '*'
